#!/usr/bin/env ruby
# frozen_string_literal: true

# Rails Routes to Collections Gem Installer
# This script helps install the gem in any Rails project

require 'fileutils'

class GemInstaller
  def initialize
    @gem_name = 'rails_routes_to_collections'
    @gem_source_path = __dir__
    @verbose = ARGV.include?('--verbose') || ARGV.include?('-v')
  end

  def run
    puts "🚀 Rails Routes to Collections Gem Installer"
    puts "=" * 50

    target_dir = ARGV.first || Dir.pwd
    
    unless rails_project?(target_dir)
      puts "❌ Error: Not a Rails project directory"
      puts "Please run from a Rails project root or specify the path:"
      puts "  ruby install.rb /path/to/rails/project"
      exit 1
    end

    install_to_project(target_dir)
  end

  private

  def rails_project?(dir)
    File.exist?(File.join(dir, 'config', 'application.rb')) &&
    File.exist?(File.join(dir, 'Gemfile'))
  end

  def install_to_project(target_dir)
    puts "📁 Target Rails project: #{target_dir}"
    
    # Create local_gems directory
    local_gems_dir = File.join(target_dir, 'local_gems')
    FileUtils.mkdir_p(local_gems_dir)
    puts "✅ Created local_gems directory" if @verbose

    # Copy gem files
    gem_target_path = File.join(local_gems_dir, @gem_name)
    if File.exist?(gem_target_path)
      puts "📦 Gem already exists, updating..."
      FileUtils.rm_rf(gem_target_path)
    end

    FileUtils.cp_r(@gem_source_path, gem_target_path)
    puts "✅ Copied gem to #{gem_target_path}"

    # Update Gemfile
    gemfile_path = File.join(target_dir, 'Gemfile')
    gemfile_content = File.read(gemfile_path)
    
    gem_line = "gem '#{@gem_name}', path: './local_gems/#{@gem_name}'"
    
    unless gemfile_content.include?(@gem_name)
      File.open(gemfile_path, 'a') do |f|
        f.puts ""
        f.puts "# Rails Routes to Collections Gem"
        f.puts gem_line
      end
      puts "✅ Added gem to Gemfile"
    else
      puts "✅ Gem already in Gemfile"
    end

    # Create convenience scripts
    create_convenience_scripts(target_dir)

    puts "\n🎉 Installation Complete!"
    puts "\n📋 Next Steps:"
    puts "1. Run: bundle install"
    puts "2. Generate collections:"
    puts "   • bundle exec rails routes:export:postman"
    puts "   • bundle exec rails routes:export:apidog"
    puts "   • ./generate_collections --format postman"
    puts "\n📖 Usage Examples:"
    puts "   ./generate_collections --format apidog --name \"My API\" --base-url https://api.myapp.com"
    puts "   bundle exec rails routes:export:all"
  end

  def create_convenience_scripts(target_dir)
    # Create CLI wrapper script
    cli_script_path = File.join(target_dir, 'generate_collections')
    File.open(cli_script_path, 'w') do |f|
      f.puts "#!/usr/bin/env ruby"
      f.puts "# frozen_string_literal: true"
      f.puts ""
      f.puts "# Rails Routes to Collections CLI"
      f.puts "# Auto-generated by gem installer"
      f.puts ""
      f.puts "require_relative 'config/environment'"
      f.puts "$LOAD_PATH.unshift File.expand_path('./local_gems/#{@gem_name}/lib', __dir__)"
      f.puts "require '#{@gem_name}'"
      f.puts ""
      f.puts "RailsRoutesToCollections::CLI.run(ARGV)"
    end
    FileUtils.chmod(0755, cli_script_path)
    puts "✅ Created CLI script: ./generate_collections"

    # Create quick generation script
    quick_script_path = File.join(target_dir, 'generate_api_collections.rb')
    File.open(quick_script_path, 'w') do |f|
      f.puts "#!/usr/bin/env ruby"
      f.puts "# frozen_string_literal: true"
      f.puts ""
      f.puts "# Quick API Collections Generator"
      f.puts "# Usage: ruby generate_api_collections.rb"
      f.puts ""
      f.puts "require_relative 'config/environment'"
      f.puts "$LOAD_PATH.unshift File.expand_path('./local_gems/#{@gem_name}/lib', __dir__)"
      f.puts "require '#{@gem_name}'"
      f.puts ""
      f.puts "puts '🚀 Generating API Collections...'"
      f.puts ""
      f.puts "extractor = RailsRoutesToCollections::RouteExtractor.new"
      f.puts "routes = extractor.extract_routes"
      f.puts "puts \"📊 Found \#{routes.length} routes\""
      f.puts ""
      f.puts "# Generate Postman collection"
      f.puts "postman_gen = RailsRoutesToCollections::PostmanGenerator.new(extractor)"
      f.puts "postman_gen.write_to_file('postman_collection.json', 'My API', 'http://localhost:3000')"
      f.puts "puts '✅ Generated: postman_collection.json'"
      f.puts ""
      f.puts "# Generate Apidog collection"
      f.puts "apidog_gen = RailsRoutesToCollections::ApidogGenerator.new(extractor)"
      f.puts "apidog_gen.write_to_file('apidog_collection.json', 'My API', 'http://localhost:3000')"
      f.puts "puts '✅ Generated: apidog_collection.json'"
      f.puts ""
      f.puts "puts '🎉 Done! Import these files into Postman or Apidog.'"
    end
    FileUtils.chmod(0755, quick_script_path)
    puts "✅ Created quick script: ./generate_api_collections.rb"
  end
end

# Run the installer
GemInstaller.new.run